feature/contacts
rostunho/team-six-icecream pull request #8
Opened 2021-07-16 15:16 UTC by svitlana-tsymbal

2021-07-16 15:35 UTC, VitaliiKarpovets commented on src/partials/contacts.html
> +        <h1 class="contacts__title">Locations</h1>
h1 в нас має бути 1 на сторінці. В даному випадку він не видимий і, можливо, це не грає ролі, але вважаю це не помилкою

2021-07-16 15:38 UTC, VitaliiKarpovets commented on src/partials/contacts.html
> +                    <span class="contacts__item__locations">CAFE</span>
Якщо я не помиляюся BEM оформлений не вірно. Для ul все добре, а далі для span і p потрібно після contacts__item ставити не подвійне нижнє підкреслювання, а подвійне тире.

2021-07-16 15:48 UTC, VitaliiKarpovets commented on src/partials/contacts.html
> +<section class="contacts">
На мою думку, обраний не вірний спосіб для розмітки даної секції. Тут, на мою думку повинен бути не список, а 3 окремих діва, тому що всередині кожного "краулера" треба буде робити оформлення.

2021-07-16 15:51 UTC, VitaliiKarpovets commented on src/partials/contacts.html
> +        <div class="contacts__button">
Аналогічно з ВЕМ, на мою думку, тут. 
В дів стоїть клас "contacts__button", всі елементи, що йдуть в цьому діві будуть мати клас "contacts__button--.....".

2021-07-16 15:54 UTC, VitaliiKarpovets commented on src/sass/layouts/_contacts.scss
> +    background-color:#F0D1A5;;
Кольори мають бути в змінних, якщо є то треба замінити тут

2021-07-16 16:02 UTC, VitaliiKarpovets commented on src/partials/contacts.html
> +                    <p><a class="contacts__link" href="noreply@envato.com">noreply@envato.com</a></p>
Для пошти аналогічно телефону треба вказати протокол. mailto

2021-07-16 16:11 UTC, svitlana-tsymbal commented on src/partials/contacts.html
> +        <h1 class="contacts__title">Locations</h1>
Згідна, зараз виправляю

2021-07-16 16:11 UTC, svitlana-tsymbal commented on src/partials/contacts.html
> +                    <span class="contacts__item__locations">CAFE</span>
block-name__elem-name--mod-name--mod-val

Имена записываются латиницей в нижнем регистре.

Для разделения слов в именах БЭМ-сущностей используется дефис (-).

Имя элемента отделяется от имени блока двумя подчеркиваниями (__).

Булевые модификаторы отделяются от имения блока или элемента двумя дефисами (--).

Значение модификатора отделяется от его имени двумя дефисами (--).

Важно! Двойной дефис внутри комментария (--) может вызвать ошибки при валидации HTML-документа.

2021-07-16 16:14 UTC, svitlana-tsymbal commented on src/partials/contacts.html
> +<section class="contacts">
В нашому ДЗ подібні однакові блоки я робила через  список.   Зауважень з боку метора не було. Тому в даному випадку я не впевнена, що потрібно виправити лі на дів

2021-07-16 22:18 UTC, svitlana-tsymbal commented on src/partials/contacts.html
> +                    <p><a class="contacts__link" href="noreply@envato.com">noreply@envato.com</a></p>
виправила

2021-07-16 22:20 UTC, svitlana-tsymbal commented on src/sass/layouts/_contacts.scss
> +    background-color:#F0D1A5;;
внесла окремо, тому що разові кольори (як вирішили на зборах)

2021-07-16 22:24 UTC, svitlana-tsymbal commented on src/partials/contacts.html
> +        <div class="contacts__button">
Виправляю

2021-07-17 05:56 UTC, rostunho requested changes
Дивіться, багато деталей цієї секції ми разом уточнили на минулій зустрічі. Тому я просто "технічно" поверну цей реквест і будемо чекати нової версії. Ок?

2021-07-18 16:17 UTC, closed without merging